# Generated by Django 4.0.3 on 2022-04-11 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_canciones_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='ID_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
